git-svn-id: svn://svn.code.sf.net/p/jawe/code/jawe@101 4bd7e58f-8986-49bf-85ab-427c71a3f9e1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -121,17 +121,21 @@ if test -n "$jdk_DOT_dir"; then
     jdk_DOT_dir=`echo $jdk_DOT_dir|sed -e 's|_DOT_|\.|g'`
     version=`echo $version|sed -e 's|_DOT_|\.|g'`
 else
-    which_javac=`which javac 2>/dev/null`
-    if test -n "$which_javac"; then
-	cd `dirname $which_javac`/..
-	jdk_DOT_dir=$PWD
-	cd -
+    if test -n "$JAVA_HOME"; then
+      jdk_DOT_dir=$JAVA_HOME
     else
-	{
-	    echo "$0: error: JAVA_HOME not defined
-Try \`$0 --help' for more information." >&2
-	    { (exit 1); exit 1; };
-	}
+      which_javac=`which javac 2>/dev/null`
+       if test -n "$which_javac"; then
+	   cd `dirname $which_javac`/..
+	   jdk_DOT_dir=$PWD
+	   cd -
+       else
+	   {
+	       echo "$0: error: JAVA_HOME not defined
+   Try \`$0 --help' for more information." >&2
+	       { (exit 1); exit 1; };
+	   }
+       fi
     fi
 fi
 
